import { BookTheme } from "./types";

export const FONTS = [
  { name: "Patrick Hand", category: "Handwritten" },
  { name: "Caveat", category: "Handwritten" },
  { name: "Kalam", category: "Handwritten" },
  { name: "Indie Flower", category: "Handwritten" },
  { name: "Architects Daughter", category: "Handwritten" },
  { name: "Fredoka", category: "Playful" },
  { name: "Sniglet", category: "Playful" },
  { name: "Baloo 2", category: "Playful" },
  { name: "Chewy", category: "Playful" },
  { name: "DynaPuff", category: "Playful" },
  { name: "Pangolin", category: "Playful" },
  { name: "Gaegu", category: "Playful" },
  { name: "Comfortaa", category: "Modern" },
  { name: "Quicksand", category: "Modern" },
  { name: "Lora", category: "Classic" },
  { name: "Amatic SC", category: "Whimsical" },
];

export const THEMES: BookTheme[] = [
  {
    id: "botanical_meadow",
    name: "Botanical Meadow",
    tagline: "Forest green binding, sage leaf borders & emerald vine corners",
    paperBg: "#f6f8f3",
    inkColor: "#1d291e",
    spineColor: "#223b28",
    borderColor: "#cfe0d0",
    accentColor: "#588157",
    frameColor: "#4f772d",
    decorType: "botanical",
    recommendedFont: "Patrick Hand",
  },
  {
    id: "celestial_nocturne",
    name: "Celestial Starlight",
    tagline: "Midnight indigo spine with golden crescent stars and cosmic corners",
    paperBg: "#1c2234",
    inkColor: "#f3f5fa",
    spineColor: "#0f1422",
    borderColor: "#2e3752",
    accentColor: "#f59e0b",
    frameColor: "#fbbf24",
    decorType: "celestial",
    recommendedFont: "Comfortaa",
  },
  {
    id: "antique_heirloom",
    name: "Antique Leather & Gold",
    tagline: "Burnished cognac leather, warm parchment with filigree corners",
    paperBg: "#faf2e3",
    inkColor: "#2b1a11",
    spineColor: "#3d1b0c",
    borderColor: "#e3d1b6",
    accentColor: "#b48448",
    frameColor: "#c69255",
    decorType: "victorian",
    recommendedFont: "Lora",
  },
  {
    id: "sakura_bloom",
    name: "Sakura Tea Garden",
    tagline: "Rose-tinted rice paper with cherry blossom twigs & coral corners",
    paperBg: "#fdf6f5",
    inkColor: "#2e1a22",
    spineColor: "#421d28",
    borderColor: "#edd6db",
    accentColor: "#e07a5f",
    frameColor: "#d9777f",
    decorType: "sakura",
    recommendedFont: "Caveat",
  },
  {
    id: "spiced_chai",
    name: "Spiced Chai & Tweed",
    tagline: "Warm terracotta paper, cozy autumn stitch lines & acorn motifs",
    paperBg: "#f7eee3",
    inkColor: "#381c12",
    spineColor: "#451e0e",
    borderColor: "#dfc7b0",
    accentColor: "#c68b59",
    frameColor: "#b06d3b",
    decorType: "chai",
    recommendedFont: "Kalam",
  },
  {
    id: "brass_study",
    name: "Vintage Brass Library",
    tagline: "Dark spruce boards with riveted brass corner brackets",
    paperBg: "#fcfbf7",
    inkColor: "#232622",
    spineColor: "#1d2924",
    borderColor: "#dedad2",
    accentColor: "#d4af37",
    frameColor: "#b89730",
    decorType: "brass",
    recommendedFont: "Fredoka",
  },
];

export const LOFI_PALETTE = [
  "#2c211a",
  "#4d3a2e",
  "#8b6d5c",
  "#c68b59",
  "#dda15e",
  "#e07a5f",
  "#606c38",
  "#819b7a",
  "#3d5a80",
  "#847596",
  "#b48448",
  "#f3f5fa",
];