import { BookFormat, BookTheme, FontOption } from "./types";

export const BOOK_FORMATS: BookFormat[] = [
  {
    id: "square",
    label: "Square Storybook",
    pageWidth: 650,
    pageHeight: 650,
    aspectRatio: "2 / 1",
    description: "Classic 8.5\" × 8.5\" picture book layout with balanced spreads.",
  },
  {
    id: "landscape",
    label: "Panoramic Landscape",
    pageWidth: 750,
    pageHeight: 520,
    aspectRatio: "2.88 / 1",
    description: "Wide 11\" × 8.5\" format ideal for sprawling scenery and panoramas.",
  },
  {
    id: "portrait",
    label: "Classic Portrait",
    pageWidth: 520,
    pageHeight: 680,
    aspectRatio: "1.53 / 1",
    description: "Standard 8\" × 10\" tall format, great for bedtime stories with lots of text.",
  },
];

export const BOOK_THEMES: BookTheme[] = [
  {
    id: "parchment_tales",
    name: "Enchanted Storybook",
    subtitle: "Aged parchment, gold spine tooling, warm fairy tale aura",
    coverColor: "#451e11",
    coverTexture: "linear-gradient(135deg, #451e11 0%, #2b120a 100%)",
    pageBackground: "#fdf8ee",
    pageOverlayStyle: "radial-gradient(circle at center, rgba(255,255,255,0.5) 0%, rgba(214,192,159,0.3) 100%)",
    spineGutterColor: "#3a190e",
    primaryFont: "Lora",
    textColor: "#2a1b12",
    accentColor: "#d4af37",
  },
  {
    id: "watercolor_coldpress",
    name: "Artisan Cold-Press",
    subtitle: "Heavy watercolor grain, woven linen binding, soft pastel tone",
    coverColor: "#1e3a34",
    coverTexture: "linear-gradient(135deg, #1e3a34 0%, #122420 100%)",
    pageBackground: "#f9f9f6",
    pageOverlayStyle: "radial-gradient(circle at center, rgba(255,255,255,0.7) 30%, rgba(220,225,222,0.4) 100%)",
    spineGutterColor: "#13231f",
    primaryFont: "Patrick Hand",
    textColor: "#1d2a24",
    accentColor: "#52b788",
  },
  {
    id: "celestial_nocturne",
    name: "Celestial Midnight",
    subtitle: "Starlight blue paper, silver-edged binding, magical night sky feel",
    coverColor: "#0d1322",
    coverTexture: "linear-gradient(135deg, #131b2e 0%, #080c16 100%)",
    pageBackground: "#161b28",
    pageOverlayStyle: "radial-gradient(circle at 50% 30%, rgba(42,54,82,0.4) 0%, rgba(15,18,28,0.7) 100%)",
    spineGutterColor: "#0b0f19",
    primaryFont: "Fredoka",
    textColor: "#edf2f7",
    accentColor: "#6366f1",
  },
  {
    id: "botanical_herbarium",
    name: "Vintage Botanical",
    subtitle: "Pressed sage flora, warm deckle edges, hand-bound naturalist look",
    coverColor: "#283618",
    coverTexture: "linear-gradient(135deg, #283618 0%, #19220f 100%)",
    pageBackground: "#f4f7f2",
    pageOverlayStyle: "radial-gradient(circle at center, rgba(255,255,255,0.6) 20%, rgba(206,217,201,0.4) 100%)",
    spineGutterColor: "#1a2410",
    primaryFont: "Caveat",
    textColor: "#1c2b18",
    accentColor: "#dda15e",
  },
  {
    id: "royal_velvet",
    name: "Crimson Heirloom",
    subtitle: "Plush velvet book jacket, gilded edges, warm candlelight glow",
    coverColor: "#3d0c11",
    coverTexture: "linear-gradient(135deg, #4a0e14 0%, #29060a 100%)",
    pageBackground: "#fcf6f0",
    pageOverlayStyle: "radial-gradient(circle at center, rgba(255,255,255,0.5) 10%, rgba(235,214,198,0.4) 100%)",
    spineGutterColor: "#2b0609",
    primaryFont: "Sniglet",
    textColor: "#33181a",
    accentColor: "#e63946",
  },
];

export const FONTS: FontOption[] = [
  { family: "Lora", label: "Lora (Fairy Tale Classic)", category: "Storybook" },
  { family: "Patrick Hand", label: "Patrick Hand (Warm Handwritten)", category: "Handwritten" },
  { family: "Fredoka", label: "Fredoka (Rounded & Bubbly)", category: "Playful" },
  { family: "Caveat", label: "Caveat (Flowing Ink Pen)", category: "Handwritten" },
  { family: "Sniglet", label: "Sniglet (Cute Children's Font)", category: "Playful" },
  { family: "DynaPuff", label: "DynaPuff (Animated & Fun)", category: "Playful" },
  { family: "Gaegu", label: "Gaegu (Casual Marker)", category: "Handwritten" },
  { family: "Comfortaa", label: "Comfortaa (Minimal Picturebook)", category: "Storybook" },
];

export const COLOR_PALETTE = [
  "#ffffff",
  "#e2e8f0",
  "#94a3b8",
  "#f87171",
  "#fb923c",
  "#facc15",
  "#4ade80",
  "#2dd4bf",
  "#38bdf8",
  "#818cf8",
  "#c084fc",
  "#f472b6",
  "#3d1e11",
  "#14241d",
  "#0f172a",
];